// <auto-generated />
using ListRecommendations.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ListRecommendations.Migrations
{
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
    }
}
