// <auto-generated />
using ListRecommendations.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ListRecommendations.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("ListRecommendations.Models.Favorite", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("routeInfo")
                    .HasColumnType("TEXT");

                b.Property<string>("routeMark")
                    .HasColumnType("TEXT");

                b.Property<string>("routeName")
                    .HasColumnType("TEXT");

                b.HasKey("ID");

                b.ToTable("Favorite");
            });

            modelBuilder.Entity("ListRecommendations.Models.Users", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("login")
                    .HasColumnType("TEXT");

                b.Property<string>("password")
                    .HasColumnType("TEXT");

                b.HasKey("id");

                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}
